# Generated by Django 2.1.4 on 2019-01-04 02:37

from django.db import migrations
import home.models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'homepage'},
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='external_portfolio_links',
            field=wagtail.core.fields.StreamField([('links', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(label='link text', required=False)), ('external_url', wagtail.core.blocks.URLBlock(label='external URL', required=True))]))], blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='portfolio_information',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('contact_email', wagtail.core.blocks.EmailBlock())], blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='project_images',
            field=wagtail.core.fields.StreamField([('project_example', wagtail.core.blocks.ListBlock(home.models.ProjectImageBlock))], blank=True),
        ),
    ]
