# Generated by Django 2.1.4 on 2019-01-04 03:01

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190104_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact_email',
            field=wagtail.core.fields.StreamField([('contact_email', wagtail.core.blocks.EmailBlock())], blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='portfolio_information',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('paragraph', wagtail.core.blocks.TextBlock())], blank=True),
        ),
    ]
