# Generated by Django 2.1.5 on 2019-01-15 01:57

from django.db import migrations
import home.models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190104_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='external_portfolio_links',
            field=wagtail.core.fields.StreamField([('links', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(default='portfolio link', label='link text')), ('external_url', wagtail.core.blocks.URLBlock(default='#', label='external URL'))]))]),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='portfolio_information',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(default='Portfolio Title')), ('paragraph', wagtail.core.blocks.TextBlock(default='Portfolio Subheading'))]),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='project_images',
            field=wagtail.core.fields.StreamField([('project_example', wagtail.core.blocks.ListBlock(home.models.ProjectImageBlock, template='blocks/portfolio_image.html'))], blank=True),
        ),
    ]
