# Generated by Django 2.1.5 on 2019-01-19 20:54

from django.db import migrations, models
import django.db.models.deletion
import portfolio.models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro_title', models.CharField(blank=True, help_text='Optional H1 title for the gallery page.', max_length=250, verbose_name='Intro title')),
                ('intro_text', wagtail.core.fields.RichTextField(blank=True, help_text='Optional text to go with the intro text.', verbose_name='Intro text')),
                ('order_items_by', models.IntegerField(choices=[(1, 'Order number'), (2, 'Newest item first')], default=1)),
                ('portfolio_items', wagtail.core.fields.StreamField([('portfolio_item', wagtail.core.blocks.ListBlock(portfolio.models.PortfolioItemBlock, template='blocks/portfolio_item.html'))], blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
