# Generated by Django 2.1.5 on 2019-01-19 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioindexpage',
            options={'verbose_name': 'portfolio'},
        ),
    ]
